# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'business.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_business(object):
    def setupUi(self, business):
        business.setObjectName("business")
        business.resize(678, 466)
        self.gridLayout = QtWidgets.QGridLayout(business)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(business)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(business)
        self.label.setMinimumSize(QtCore.QSize(0, 24))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.widget = QtWidgets.QWidget(business)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.widget)
        self.dateEdit_2.setDate(QtCore.QDate(2021, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_2.addWidget(self.dateEdit_2, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.buttonGroup = QtWidgets.QButtonGroup(business)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBox_2)
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.buttonGroup.addButton(self.checkBox)
        self.gridLayout_2.addWidget(self.checkBox, 0, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.widget)
        self.dateEdit.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 3)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(business)
        QtCore.QMetaObject.connectSlotsByName(business)

    def retranslateUi(self, business):
        _translate = QtCore.QCoreApplication.translate
        business.setWindowTitle(_translate("business", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("business", "支行名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("business", "用户数"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("business", "总金额"))
        self.label.setText(_translate("business", "业务统计"))
        self.label_4.setText(_translate("business", "结束时间"))
        self.checkBox_2.setText(_translate("business", "贷款"))
        self.label_2.setText(_translate("business", "起始时间"))
        self.checkBox.setText(_translate("business", "储蓄"))
        self.label_3.setText(_translate("business", "业务分类"))
        self.pushButton.setText(_translate("business", "Search"))
