# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionManage_Customers = QtWidgets.QAction(MainWindow)
        self.actionManage_Customers.setObjectName("actionManage_Customers")
        self.actionssdf = QtWidgets.QAction(MainWindow)
        self.actionssdf.setObjectName("actionssdf")
        self.actionManage_Accounts = QtWidgets.QAction(MainWindow)
        self.actionManage_Accounts.setObjectName("actionManage_Accounts")
        self.actionManage_Loans = QtWidgets.QAction(MainWindow)
        self.actionManage_Loans.setObjectName("actionManage_Loans")
        self.actionBusiness_Statistics = QtWidgets.QAction(MainWindow)
        self.actionBusiness_Statistics.setObjectName("actionBusiness_Statistics")
        self.menu.addAction(self.actionManage_Customers)
        self.menu.addAction(self.actionManage_Accounts)
        self.menu.addAction(self.actionManage_Loans)
        self.menu.addAction(self.actionBusiness_Statistics)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "功能选择"))
        self.actionManage_Customers.setText(_translate("MainWindow", "Manage Customers"))
        self.actionssdf.setText(_translate("MainWindow", "ssdf"))
        self.actionManage_Accounts.setText(_translate("MainWindow", "Manage Account"))
        self.actionManage_Loans.setText(_translate("MainWindow", "Manage Loans"))
        self.actionBusiness_Statistics.setText(_translate("MainWindow", "Business Statistics"))
